"""
Django settings for tennis_tracker_site project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY='dev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=True

# add production domain here
ALLOWED_HOSTS=[
    'local host',
    '127.0.0.1'
]

# Application definition
INSTALLED_APPS=[
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'tracker'
]


MIDDLEWARE=[]

ROOT_URLCONF='backend.urls'

# --- Ensure ASGI Application is set for Channels ---
ASGI_APPLICATION='backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# MySQL database connection
DATABASES={
    'default':
    {'ENGINE':'django.db.backends.mysql',
     'NAME':'tennis_tracker',
     'USER':'root',
     'PASSWORD':'password',
     'HOST':'localhost',
     'PORT':'3306'
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR/'media'
CHANNEL_LAYERS={'default':{'BACKEND':'channels.layers.InMemoryChannelLayer'}}